# .streamlit/pages.toml

[pages]
"app.py" = {name = "Main", icon = "ğŸ "}
"pages/1_Login.py" = {name = "Login", icon = "ğŸ”‘"}
"pages/2_Overview.py" = {name = "Overview", icon = "ğŸ“Š"}
"pages/3_StudentList.py" = {name = "Student List", icon = "ğŸ“‹"}
"pages/4_StudentDetail.py" = {name = "Student Details", icon = "ğŸ‘¤"}
"pages/5_FeatureContribution.py" = {name = "Analysis", icon = "ğŸ“ˆ"}